# Generated by Django 3.0.5 on 2020-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=500)),
                ('Condition', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Created', models.DateTimeField()),
            ],
        ),
    ]
