# Generated by Django 3.0.5 on 2020-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('product', '0006_auto_20200426_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
